region: ap-northeast-1

function_name: slack_learning_app_ja
handler: lambda_app.handler
description: 日本語で学ぶ Slack アプリ
runtime: python3.8
role: slack_dev_learning_app_role

# S3 upload requires appropriate role with s3:PutObject permission
# (ex. basic_s3_upload), a destination bucket, and the key prefix
# bucket_name: 'example-bucket'
# s3_key_prefix: 'path/to/file/'

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
# timeout: 15
# memory_size: 512
# concurrency: 500
#

# Experimental Environment variables
environment_variables:
    SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
    SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
    SLACK_SCOPES: ${SLACK_SCOPES}
    SLACK_INSTALLATION_S3_BUCKET_NAME: ${SLACK_INSTALLATION_S3_BUCKET_NAME}
    SLACK_STATE_S3_BUCKET_NAME: ${SLACK_STATE_S3_BUCKET_NAME}
    SLACK_LAMBDA_PATH: ${SLACK_LAMBDA_PATH}
    SLACK_LANGUAGE: ${SLACK_LANGUAGE}

# If `tags` is uncommented then tags will be set at creation or update
# time.  During an update all other tags will be removed except the tags
# listed here.
#tags:
#    tag_1: foo
#    tag_2: bar

# Build options
build:
  source_directories: "app" # a comma delimited list of directories in your project root that contains source to package.
